#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
easy_admin:
    entities:
        User:
            class: App\Entity\User
            list:
                title: 'Usuarios'
        Categories:
            class: App\Entity\Categories
            list:
                title: 'Categorias'
        Services:
            class: App\Entity\Services
            list:
                title: 'Todos los servicios'

